DROP DATABASE IF EXISTS krautundrueben;
CREATE DATABASE IF NOT EXISTS krautundrueben;
USE krautundrueben;


# Kunden Tabelle erstellen
CREATE TABLE KUNDE (
    KUNDENNR        INTEGER NOT NULL,
    NACHNAME        VARCHAR(50),
    VORNAME         VARCHAR(50),
    GEBURTSDATUM    DATE,
    STRASSE         VARCHAR(50),
    HAUSNR          VARCHAR(6),
    PLZ             VARCHAR(5),
    ORT             VARCHAR(50),
    TELEFON         VARCHAR(25),
    EMAIL           VARCHAR(50)
);

# Zutaten Tabelle erstellen
CREATE TABLE ZUTAT(
    ZUTATENNR       INTEGER NOT NULL,
    BEZEICHNUNG     VARCHAR(50),
    EINHEIT         VARCHAR (25),
    NETTOPREIS      DECIMAL(10,2),
    BESTAND         INTEGER,
    LIEFERANT       INTEGER,
    KALORIEN        INTEGER,
    KOHLENHYDRATE   DECIMAL (10,2),
    PROTEIN         DECIMAL(10,2)
);

# Bestellungs Tabelle erstellen
CREATE TABLE BESTELLUNG (
    BESTELLNR        INTEGER AUTO_INCREMENT NOT NULL,
    KUNDENNR         INTEGER,
    BESTELLDATUM     DATE,
    RECHNUNGSBETRAG  DECIMAL(10,2),
    PRIMARY KEY (BESTELLNR)
);

# Verbindungs Tabelle zwischen Zutaten und Bestellung erstellen
CREATE TABLE BESTELLUNGZUTAT (
    BESTELLNR       INTEGER NOT NULL,
    ZUTATENNR       INTEGER,
    MENGE           INTEGER
);

# Lieferaten Tabelle erstellen
CREATE TABLE LIEFERANT (
    LIEFERANTENNR   INTEGER NOT NULL,
    LIEFERANTENNAME VARCHAR(50),
    STRASSE         VARCHAR(50),
    HAUSNR          VARCHAR(6),
    PLZ             VARCHAR(5),
    ORT             VARCHAR(50),
    TELEFON         VARCHAR(25),
    EMAIL           VARCHAR(50)
);

# Rezept Tabelle erstellen
CREATE TABLE REZEPT (
    REZEPTNR      INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    REZEPTNAME    VARCHAR(50)
);

# Verbindungs Tabelle zwischen Zutaten und Rezepten erstellen
CREATE TABLE REZEPTZUTAT (
    ZUTATENNR     INTEGER NOT NULL,
    REZEPTNR      INTEGER NOT NULL,
    MENGE         INTEGER,
    PRIMARY KEY (ZUTATENNR, REZEPTNR)
);

# Beschränkungs Tabelle erstellen
CREATE TABLE BESCHRAENKUNGEN (
    BESCHRAENKUNGS_ID     INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    BESCHRAENKUNGSNAME    VARCHAR(50)
);

# Verbindungs Tabelle zwischen Rezepten und Beschränkungen erstellen
CREATE TABLE BESCHRAENKUNGENREZEPT (
    BESCHRAENKUNGS_ID     INTEGER NOT NULL,
    REZEPTNR              INTEGER NOT NULL,
    PRIMARY KEY (BESCHRAENKUNGS_ID, REZEPTNR)
);

# Ernährungskategorie Tabelle erstellen
Create TABLE ERNAEHRUNGSKATEGORIEN (
    ERNAEHRUNGSKATEGORIE_ID     INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    ERNAEHRUNGSKATEGORIENAME    VARCHAR(50)
);

# Verbindungs Tabelle zwischen Rezepten und Ernährungskategorien erstellen
CREATE TABLE ERNAEHRUNGKATREZEPT (
    ERNAEHRUNGSKATEGORIE_ID    INTEGER NOT NULL,
    REZEPTNR                   INTEGER NOT NULL
);

# Preis Änderungs Tabelle erstellen
CREATE TABLE PREIS_AENDERUNGEN (
    ID                  INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ZUTATENNR           INTEGER NOT NULL,
    ALTER_PREIS         DECIMAL(10,2),
    NEUER_PREIS         DECIMAL(10,2),
    VERANTWORTLICHER    VARCHAR(50),
    ZEITPUNKT           TIMESTAMP
);

/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/


ALTER TABLE ZUTAT ADD PRIMARY KEY (ZUTATENNR);
ALTER TABLE KUNDE ADD PRIMARY KEY (KUNDENNR);
ALTER TABLE LIEFERANT ADD PRIMARY KEY (LIEFERANTENNR);
ALTER TABLE BESTELLUNGZUTAT ADD PRIMARY KEY (BESTELLNR,ZUTATENNR);
ALTER TABLE ERNAEHRUNGKATREZEPT ADD PRIMARY KEY (ERNAEHRUNGSKATEGORIE_ID, REZEPTNR);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE ZUTAT ADD FOREIGN KEY (LIEFERANT) REFERENCES LIEFERANT (LIEFERANTENNR);
ALTER TABLE BESTELLUNGZUTAT ADD FOREIGN KEY (BESTELLNR) REFERENCES BESTELLUNG (BESTELLNR);
ALTER TABLE BESTELLUNG ADD FOREIGN KEY (KUNDENNR) REFERENCES KUNDE (KUNDENNR);
ALTER TABLE BESTELLUNGZUTAT ADD FOREIGN KEY (ZUTATENNR) REFERENCES ZUTAT (ZUTATENNR);
ALTER TABLE REZEPTZUTAT ADD FOREIGN KEY (ZUTATENNR) REFERENCES ZUTAT (ZUTATENNR);
ALTER TABLE REZEPTZUTAT ADD FOREIGN KEY (REZEPTNR) REFERENCES REZEPT (REZEPTNR);
ALTER TABLE ERNAEHRUNGKATREZEPT ADD FOREIGN KEY (REZEPTNR) REFERENCES REZEPT (REZEPTNR);
ALTER TABLE ERNAEHRUNGKATREZEPT ADD FOREIGN KEY (ERNAEHRUNGSKATEGORIE_ID) REFERENCES ERNAEHRUNGSKATEGORIEN (ERNAEHRUNGSKATEGORIE_ID);
ALTER TABLE BESCHRAENKUNGENREZEPT ADD FOREIGN KEY (BESCHRAENKUNGS_ID) REFERENCES BESCHRAENKUNGEN (BESCHRAENKUNGS_ID);
ALTER TABLE BESCHRAENKUNGENREZEPT ADD FOREIGN KEY (REZEPTNR) REFERENCES REZEPT (REZEPTNR);
ALTER TABLE PREIS_AENDERUNGEN ADD FOREIGN KEY (ZUTATENNR) REFERENCES ZUTAT (ZUTATENNR);


/******************************************************************************/
/***                           Stored Procedures                            ***/
/******************************************************************************/

DELIMITER //

# Auswahl aller Zutaten, die bisher keinem Rezept zugeordnet sind
CREATE PROCEDURE ZutatenOhneRezept()
BEGIN
    SELECT ZUTAT.BEZEICHNUNG
    FROM ZUTAT
    LEFT JOIN REZEPTZUTAT ON ZUTAT.ZUTATENNR = REZEPTZUTAT.ZUTATENNR
	 WHERE REZEPTZUTAT.ZUTATENNR IS NULL;
END//

# Auswahl aller Rezepte einer bestimmten Ernährungskategorie
CREATE PROCEDURE RezepteMitErnaehrungskategorie(IN ErnaehrungskategorieName_ VARCHAR(50))
BEGIN
    SELECT REZEPT.REZEPTNAME
    FROM ERNAEHRUNGSKATEGORIEN
    INNER JOIN ERNAEHRUNGKATREZEPT ON ERNAEHRUNGSKATEGORIEN.ERNAEHRUNGSKATEGORIE_ID = ERNAEHRUNGKATREZEPT.ERNAEHRUNGSKATEGORIE_ID
    INNER JOIN REZEPT ON ERNAEHRUNGKATREZEPT.REZEPTNR = REZEPT.REZEPTNR
    WHERE ERNAEHRUNGSKATEGORIEN.ERNAEHRUNGSKATEGORIENAME = ErnaehrungskategorieName_;
END//

# Auswahl aller Rezepte, die weniger als fünf Zutaten enthalten und eine bestimmte Ernährungskategorie erfüllen
CREATE PROCEDURE RezepteMitWenigerAlsFuenfZutatenUndErneahrungskategorie(IN ErnaehrungskategorieName_ VARCHAR(50))
BEGIN
    SELECT REZEPT.REZEPTNAME
    FROM REZEPT
    WHERE 5 > (
        SELECT COUNT(REZEPTZUTAT.ZUTATENNR)
        FROM REZEPTZUTAT
        WHERE REZEPTZUTAT.REZEPTNR = REZEPT.REZEPTNR
    ) AND REZEPT.REZEPTNR IN (
        SELECT REZEPT.REZEPTNR
        FROM ERNAEHRUNGSKATEGORIEN
        INNER JOIN ERNAEHRUNGKATREZEPT ON ERNAEHRUNGSKATEGORIEN.ERNAEHRUNGSKATEGORIE_ID = ERNAEHRUNGKATREZEPT.ERNAEHRUNGSKATEGORIE_ID
        INNER JOIN REZEPT ON ERNAEHRUNGKATREZEPT.REZEPTNR = REZEPT.REZEPTNR
        WHERE ERNAEHRUNGSKATEGORIEN.ERNAEHRUNGSKATEGORIENAME = ErnaehrungskategorieName_
    );
END//

# Auswahl aller Zutaten eines Rezeptes nach Rezeptname
CREATE PROCEDURE ZutatenVonRezept(IN RezeptName_ VARCHAR(50))
BEGIN
    SELECT ZUTAT.BEZEICHNUNG
    FROM REZEPT
    INNER JOIN REZEPTZUTAT ON REZEPT.REZEPTNR = REZEPTZUTAT.REZEPTNR
    INNER JOIN ZUTAT ON REZEPTZUTAT.ZUTATENNR = ZUTAT.ZUTATENNR
    WHERE REZEPT.REZEPTNAME = RezeptName_;
END//

# Auswahl aller Rezepte, die weniger als fünf Zutaten enthalten
CREATE PROCEDURE RezepteMitWenigerAlsFuenfZutaten()
BEGIN
    SELECT REZEPT.REZEPTNAME
    FROM REZEPT
    WHERE 5 > (
        SELECT COUNT(REZEPTZUTAT.ZUTATENNR)
        FROM REZEPTZUTAT
        WHERE REZEPTZUTAT.REZEPTNR = REZEPT.REZEPTNR
    );
END//

# Berechnung der durchschnittlichen Nährwerte aller Bestellungen eines Kunden
CREATE PROCEDURE DurchschnittlicheNaehrwerteAllerBestellungEinesKunden(IN KundenNR_ INT)
BEGIN
    SELECT KUNDE.KUNDENNR,
        AVG(ZUTAT.KALORIEN*BESTELLUNGZUTAT.MENGE) AS "Durchschnittliche Kalorien",
        AVG(ZUTAT.KOHLENHYDRATE*BESTELLUNGZUTAT.MENGE) AS "Durchschnittliche Kohlenhydrate",
        AVG(ZUTAT.PROTEIN*BESTELLUNGZUTAT.MENGE) AS "Durchschnittliche Proteine"
    FROM KUNDE
    INNER JOIN BESTELLUNG ON KUNDE.KUNDENNR = BESTELLUNG.KUNDENNR
    INNER JOIN BESTELLUNGZUTAT ON BESTELLUNG.BESTELLNR = BESTELLUNGZUTAT.BESTELLNR
    INNER JOIN ZUTAT ON BESTELLUNGZUTAT.ZUTATENNR = ZUTAT.ZUTATENNR
    GROUP BY KUNDE.KUNDENNR
    HAVING KUNDE.KUNDENNR = KundenNR_;
END//

# Alle Rezepte, ohne eine bestimmte Beschraenkung
CREATE PROCEDURE RezepteOhneBeschraenkungen(IN BeschraenkungsName_ VARCHAR(50))
BEGIN
    SELECT REZEPT.REZEPTNAME
    FROM REZEPT
    WHERE (
        SELECT COUNT(BESCHRAENKUNGEN.BESCHRAENKUNGS_ID)
        FROM BESCHRAENKUNGENREZEPT
        INNER JOIN BESCHRAENKUNGEN ON BESCHRAENKUNGENREZEPT.BESCHRAENKUNGS_ID = BESCHRAENKUNGEN.BESCHRAENKUNGS_ID
        WHERE BESCHRAENKUNGENREZEPT.REZEPTNR = REZEPT.REZEPTNR AND BESCHRAENKUNGEN.BESCHRAENKUNGSNAME = BeschraenkungsName_
    ) = 0;
END//

# Auswahl aller Rezepte, die eine bestimmte Kalorienmenge nicht überschreiten
CREATE PROCEDURE RezepteMitWenigerAlsEinerBestimmtenKalorienMenge(IN Kalorien_ INT)
BEGIN
    SELECT REZEPT.REZEPTNAME
    FROM REZEPT
    INNER JOIN REZEPTZUTAT ON REZEPT.REZEPTNR = REZEPTZUTAT.REZEPTNR
    INNER JOIN ZUTAT ON ZUTAT.ZUTATENNR = REZEPTZUTAT.ZUTATENNR
    GROUP BY REZEPT.REZEPTNR 
    HAVING SUM(REZEPTZUTAT.MENGE * ZUTAT.KALORIEN) <= Kalorien_;
END//

# Auswahl aller Rezepte, die eine gewisse Zutat enthalten
CREATE PROCEDURE RezepteMitBestimmterZutat(IN Bezeichnung_ VARCHAR(50))
BEGIN
    SELECT REZEPT.REZEPTNAME
    FROM REZEPT
    INNER JOIN REZEPTZUTAT ON REZEPTZUTAT.REZEPTNR = REZEPT.REZEPTNR
    INNER JOIN ZUTAT ON ZUTAT.ZUTATENNR = REZEPTZUTAT.ZUTATENNR
    WHERE ZUTAT.BEZEICHNUNG = Bezeichnung_;
END//

# Alle Lieferanten, die die Zutaten für ein bestimmtes Rezept liefern
CREATE PROCEDURE LieferantenAllerZutatenEinesBestimmtenRezeptes(IN RezeptName_ VARCHAR(50))
BEGIN
    SELECT DISTINCT LIEFERANT.LIEFERANTENNAME
    FROM LIEFERANT 
    INNER JOIN ZUTAT ON LIEFERANT.LIEFERANTENNR = ZUTAT.LIEFERANT
    INNER JOIN REZEPTZUTAT ON REZEPTZUTAT.ZUTATENNR = ZUTAT.ZUTATENNR
    INNER JOIN REZEPT ON REZEPT.REZEPTNR = REZEPTZUTAT.REZEPTNR
    WHERE REZEPT.REZEPTNAME = RezeptName_;
END//

# Alle Rezepte inklusive ihrer Nährwerte auflisten
CREATE PROCEDURE AlleNaehrwerteAllerRezepte()
BEGIN
    SELECT REZEPT.REZEPTNAME, SUM(ZUTAT.KALORIEN * REZEPTZUTAT.MENGE) AS "Kalorien", SUM(ZUTAT.KOHLENHYDRATE * REZEPTZUTAT.MENGE) AS "Kohlenhydrate", SUM(ZUTAT.PROTEIN * REZEPTZUTAT.MENGE) AS "Protein"
    FROM REZEPT
    INNER JOIN REZEPTZUTAT ON REZEPT.REZEPTNR = REZEPTZUTAT.REZEPTNR
    INNER JOIN ZUTAT ON REZEPTZUTAT.ZUTATENNR = ZUTAT.ZUTATENNR
    GROUP BY REZEPT.REZEPTNR;
END//


DELIMITER ;

/******************************************************************************/
/***                                 Views                                  ***/
/******************************************************************************/

CREATE VIEW LIEFERANTEN_UEBERBLICK AS
SELECT ZUTAT.BEZEICHNUNG, LIEFERANT.LIEFERANTENNAME
FROM ZUTAT
INNER JOIN LIEFERANT ON ZUTAT.LIEFERANT = LIEFERANT.LIEFERANTENNR
ORDER BY LIEFERANT.LIEFERANTENNR;

/******************************************************************************/
/***                               Triggers                                 ***/
/******************************************************************************/

DELIMITER //

CREATE TRIGGER PreisAenderungen AFTER
UPDATE ON ZUTAT
FOR EACH ROW
BEGIN
    IF (OLD.NETTOPREIS != NEW.NETTOPREIS) THEN
        INSERT INTO PREIS_AENDERUNGEN (ZUTATENNR, ALTER_PREIS, NEUER_PREIS, VERANTWORTLICHER, ZEITPUNKT)
        VALUES (NEW.ZUTATENNR, OLD.NETTOPREIS, NEW.NETTOPREIS, CURRENT_USER, NOW());
    END IF;
END//

DELIMITER ;